config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get     "signin" => "devise/sessions#new"
    post    "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  get "help", to: "help#index"

  scope module: 'guest' do
    # concern :paginatable do
    #   get '(page/:page)', action: :index, on: :collection, as: ''
    # end
    root '/guest/home#index'
    get "exam/intro", to: "exam#intro"
    get "exam/check_code", to:  "exam#check_code"
    put "exam/answer", to: "exam#answer"
    post "exam/handle_example", to: "exam#handle_example"
    resources :home #, concerns: :paginatable
    resources :users
    resources :example
    resources :exam
    get "paticipant/history", to: "history#index"
  end

  scope module: 'creator' do
    resources :categories
    resources :tickets
    # resources :questions
    get "creator/question/change", to: "questions#new"
    post "creator/question", to: "questions#create"
    delete "creator/question", to: "questions#destroy"
    resources :subtickets
    # resources :history
    get "creator/history", to: "history#index"
    get "creator/download", to: "subtickets#download", format: "docx"
    get "creator/download-answer", to: "subtickets#download_answer", format: "docx"
  end
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subticket.rb
class Subticket < ApplicationRecord
  belongs_to :ticket

end

app/controllers/creator/categories_controller.rb
class Creator::CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(user_id: current_user.id, delete_at: nil)
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    category.user_id = current_user.id
    
    if category.save
      @categories = Category.where(user_id: current_user.id, delete_at: nil)
      render :index
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    if category.update(category_params)
      @categories = Category.where(user_id: current_user.id, delete_at: nil)
      render :index
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.delete_at = Time.now
    if category.save
      @categories = Category.where(user_id: current_user.id, delete_at: nil)
      render :index
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name_category, :image)
  end
end

app/controllers/creator/history_controller.rb
class Creator::HistoryController < ApplicationController
  before_action :authenticate_user!

  def index
    @historys = Ticket.all.where(user_id: current_user.id)
  end

end

app/controllers/creator/questions_controller.rb
class Creator::QuestionsController < ApplicationController
  before_action :authenticate_user!
  def new
    @question = Question.find(params[:code])
  end
  def create
    question = Question.find(params[:question_id])
    question.update_columns(question: params[:question])
    question.answers.each do |ans|
      ans.update_columns(option_value: params["#{ans.id}"])
    end
    redirect_to ticket_path(question.ticket_id)
  end

  def destroy
    question = Question.find(params[:code])
    question.update_columns(delete_at: Time.now)
    redirect_to ticket_path(question.ticket_id)
  end
end

app/controllers/creator/subtickets_controller.rb
class Creator::SubticketsController < ApplicationController
  before_action :authenticate_user!
  respond_to :docx

  def index
     @subtickets = Ticket.find(params[:code]).subtickets.where(user_id: current_user.id, delete_at: nil)
     
     if @subtickets.empty?
      redirect_to tickets_path
     end
  end
  
  def new
    ticket_id = Ticket.find(params[:code]).id
    @subticket = Subticket.new
    @subticket.ticket_id = ticket_id
    @subticket.user_id   = current_user.id
    @subticket
  end

  def show
    @subticket = Subticket.find(params[:id])
  end

  def destroy
    subticket = Subticket.find(params[:id])
    subticket.delete_at = Time.now
    subticket.save
    @subtickets = Subticket.where(user_id: current_user.id, delete_at: nil)
    render :index
  end

  def create
    for i in 0..(sub_params[:subticket_code].to_i) do
      break if i >= sub_params[:subticket_code].to_i
      code = random_sub_code
      subticket = Subticket.new
      subticket.ticket_id = sub_params[:ticket_id]
      subticket.user_id   = sub_params[:user_id]
      sub_content = []
      Ticket.find(sub_params[:ticket_id]).questions.shuffle.each do |question|
        data = []
        data.push(question.id)
        ans = []
        question.answers.shuffle.each do |answer|
          ans.push(answer.id)
        end
        data.push(ans)
        sub_content.push(data)
      end
      subticket.sub_content = sub_content
      subticket.subticket_code = code
      subticket.save
    end
    @subtickets = Subticket.all.where(ticket_id: sub_params[:ticket_id])
    render :index
  end

  def download 
    @subticket = Subticket.find(params[:code])
    respond_to do |format|
      format.docx do
        render docx: 'download', filename: "download-subticket-#{@subticket.subticket_code.to_s}.docx"
      end
    end
  end

  def download_answer
    @subticket = Subticket.find(params[:code])
    respond_to do |format|
      format.docx do
        render docx: 'download_answer_correct', filename: "download-answer-correct-subticket-#{@subticket.subticket_code.to_s}.docx"
      end
    end
  end

  private

  def sub_params
    params.require(:subticket).permit(:subticket_code, :ticket_id, :user_id)
  end

  def random_sub_code
    rand(100..999)
  end

end

app/controllers/creator/tickets_controller.rb
class Creator::TicketsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tickets = Ticket.where(user_id: current_user.id, delete_at: nil)
  end

  def new
    @ticket = Ticket.new
  end

  def create
     
    begin  
      ticket = Ticket.new(ticket_params)
      ticket.user_id = current_user.id
      
      if ticket.save
        if get_file[:file]
          data = read_file(get_file[:file])
      
          data.each do |item|
            ques        = item[:question]
            answers     = item[:answer]
            question    = Question.new 
            question.question  = ques
            question.ticket_id = ticket.id
           
            if question.save
              
              answers.each do |value|
                answer = Answer.new 
                answer.option_value = value.split("!!!T").join(",")
                correct = false
                if value.index("!!T") != nil
                  correct = true
                end
                answer.is_correct = correct
                answer.question_id  = question.id
                answer.save
              end
            end
          end
          redirect_to tickets_path

        end
      else
        redirect_to new_ticket_path
      end
    rescue => exception
      redirect_to new_ticket_path
    end
  end

  def show
    @tickets = Ticket.find(params[:id]).questions.where(delete_at: nil)
  end

  def edit 
    @ticket = Ticket.find(params[:id])
  end

  def update
    ticket = Ticket.find(params[:id])
    if ticket.update(ticket_params)
      @tickets = Ticket.where(user_id: current_user.id, delete_at: nil)
      render :index
    else
      @ticket = Ticket.find(params[:id])
      render :edit
    end
  end

  def destroy
    ticket = Ticket.find(params[:id])
    ticket.delete_at = Time.now
    ticket.save
    @tickets = Ticket.where(user_id: current_user.id, delete_at: nil)
    render :index
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name_ticket, :category_id, :code_quiz, :time_quiz, :date_start, :date_finish)
  end

  def get_file
    params.require(:ticket).permit(:file)
  end

  def read_file(file)
    data = ""
    

    File.foreach(file).with_index do |line, i|
        next if line == "\n"
        data += line.delete("\u007F") + " "
    end

    sub_data = []
    (data.split(/[Q]\s\d+[\.\:\?\/\)]/)).each do |item|
      next if item == ""
      sub_data.push(item.strip)
    end

    array_data = []
    index = 0
    sub_data.each do |item|
      array_data[index] = {}
      i = 0

      if item.index(")") != nil
        i = item.index(")")
      else
        i = item.index("?")
      end

      ques = item.slice(0, i + 1)
      ans = item.slice(i + 2, item.length)
      ans_ques_data = {}

      j = 0
      ans.each_line do |s|
        s = s.strip
        if s.slice(0, 2).delete('.)/:').upcase == "A"
          ans_ques_data[j] = s
          j+=1
        else
          if s.slice(0, 2).delete('.)/:').upcase == "B"
            ans_ques_data[j]  = s
            j+=1
          else
            if s.slice(0, 2).delete('.)/:').upcase == "C"
              ans_ques_data[j]  = s
              j+=1
            else
              if s.slice(0, 2).delete('.)/:').upcase == "D"
                ans_ques_data[j]  = s
                j+=1
              else
                if s.slice(0) == "1"
                  ans_ques_data[j]  = s
                  j+=1
                else
                  if s.slice(0) == "2"
                    ans_ques_data[j]  = s
                    j+=1
                  else
                    if s.slice(0) == "3"
                      ans_ques_data[j]  = s
                      j+=1
                    else
                      if s.slice(0) == "4"
                        ans_ques_data[j]  = s
                        j+=1
                      else
                        ans_ques_data[j - 1] = ans_ques_data[j - 1].to_s + " " + s
                        j-= 1
                      end
                    end
                  end
                end
              end
            end
          end
        end
        i += 1
      end
      
      ans_option = []

      ans_ques_data.each do |key, value|
        ans_option.push(value.slice(2, value.length).strip)
      end

      array_data[index][:question] = ques
      array_data[index][:answer]   = ans_option
      index += 1
    end
   
    array_data
  end

end

app/views/creator/subtickets/_list_subticket.html.erb
<tr>
  <td>
    <%= subticket.subticket_code %>
  </td>
  <td>
    <%= subticket.delete_at %>
  </td>
  <td>
  <%= subticket.delete_at %>
  </td>
  <td> 
    <%= link_to "<i class=\"fa fa-file-alt\"></i>".html_safe, subticket_path(subticket) %> | 
    <%= link_to "<i class=\"fa fa-trash-alt\"></i>".html_safe, subticket_path(subticket), method: :delete, data: { confirm: "Are you sure?" } %> 
  </td>
 
</tr>

app/views/creator/subtickets/download.docx.erb
<h1 style="text-align: center;"><%= Ticket.find(@subticket.ticket_id).name_ticket  %> </h1>
<p>Exam paper code: <%= @subticket.subticket_code %></p>
<br>
<br>
<% array_code = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] %>

<% @subticket.sub_content.each_with_index do |item, index| %> 
  <div class="form-group">
    <div class="answer-row">
      <div class="option-value-ans">
        <label>Question <%= index + 1 %>: <%= Question.find(item[0]).question %></label>
      </div>
    </div>
  </div>
  <br>
  <% item[1].each_with_index do |ans, index| %>
    <div class="form-group"> 
      <%
        code_a = ""
        code_a = array_code[index]
      %>
      <%= code_a + ". " %> <%= Answer.find(ans).option_value %>
    </div>
  <% end %>  
  <br>
<%  end %>

app/views/creator/subtickets/download_answer_correct.docx.erb
<h1 style="text-align: center;">Answer correct <%= Ticket.find(@subticket.ticket_id).name_ticket  %> </h1>
<p>Exam paper code: <%= @subticket.subticket_code %></p>
<br>
<br>

<% array_code = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'] %>

<% @subticket.sub_content.each_with_index do |item, index| %> 
  <div class="form-group">
    <div class="answer-row">
      <div class="option-value-ans">
        <label>Question <%= index + 1 %>: <%= Question.find(item[0]).question %></label>
      </div>
    </div>
  </div>
  <br>
  <% item[1].each_with_index do |ans, index| %>
    <div class="form-group">
      <%
        code_a = ""
        code_a = array_code[index]
      %>
      <% answer = Answer.find(ans) 
        next if answer.is_correct == false %>
      <%= code_a + ". " %> <%= answer.option_value %>
    </div>
  <% end %>  
  <br>
<%  end %>

app/views/creator/subtickets/index.html.erb
<%= render  "layouts/menu_creator" %>
  <div class="content-form">
    <div class="user-information">
      <div class="menu-user">
        <%= render  "layouts/user-menu" %>
      </div>
      <div class="show-infor-user">

        <div class="form-group">
          <%= link_to  "Back", ticket_path(@subtickets.first.ticket_id), class: "btn btn-dark" %>
        </div>
        <div class="show-infor-ticket">
            <h3>
              <%= Ticket.find(@subtickets.first.ticket_id).name_ticket if @subtickets.first != nil %>
            </h3>
          
          <table class="table-show">
            <thead>
              <tr>
                <th>Subticket code</th>
                <th>Deleted</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "list_subticket", collection: @subtickets, as: "subticket"  %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<%= render  "layouts/footer" %>

app/views/creator/subtickets/new.html.erb
<%= render  "layouts/menu_creator" %>
  <div class="content">
    <div class="user-information">
      <div class="menu-user">
        <%= render  "layouts/user-menu" %>
      </div>
      <div class="show-infor-user">
        <div class="form-login form-custom-edit">
          <%= form_for(@subticket) do |f| %>
            <h2>New subticket</h2>
            <%= f.text_field :ticket_id, hidden: true %>
            <%= f.text_field :user_id, hidden: true %>
            <div class="form-group">
              <%= f.label :number_of_subticket %>
              <label><i>(Max: 10 sub ticket)</i></label>
              <%= f.number_field :subticket_code, max: 10, min: 0,  class: "form-control", placeholder: "Enter the number of subticket you want to create" %>
            </div>

            <div class="options">
              <%= link_to  "Back", :back, class: "btn btn-dark" %>
              <%= f.submit "Create subticket", class: "btn btn-primary" %>
            </div>
          
          <% end %>
        </div>
      </div>
    </div>
  </div>
<%= render  "layouts/footer" %>

app/views/creator/subtickets/show.html.erb
<div class="container">
<%= render  "layouts/menu_creator" %>
  <div class="content">
    <div class="user-information">
      <div class="menu-user">
        <%= render  "layouts/user-menu" %>
      </div>
      
      <div class="show-infor-user">
        <div class="form-group">
          <%= link_to  "Back", subtickets_path(code: @subticket.ticket_id), class: "btn btn-dark" %><br><br>
          <%= link_to "<i class=\"fas fa-download\"></i><br> <small>Questions</small>".html_safe, creator_download_path(code: @subticket.id), class: "btn btn-outline-primary"  %> <br><br>
          <%= link_to "<i class=\"fas fa-download\"></i><br> <small>Answers</small>".html_safe, creator_download_answer_path(code: @subticket.id), class: "btn btn-outline-primary"  %> 
        </div>
        <div class="ticket-show-ans-ques">

          <% @subticket.sub_content.each_with_index do |item, index| %> 
            <div class="form-group">
              <div class="answer-row">
                <div class="option-value-ans">
                  <label>Question <%= index + 1 %>:
                    <%= Question.find(item[0]).question %>
                  </label>
                </div>
              </div>
            </div>

            <% item[1].each_with_index do |ans, index| %>
              <div class="form-group"> 
                <%
                  code_a = ""
                  code_a = "A)" if index == 0
                  code_a = "B)" if index == 1
                  code_a = "C)" if index == 2
                  code_a = "D)" if index == 3

                %>
                <%= code_a %> <%= Answer.find(ans).option_value %>
              </div>
            <% end %>  

          <%  end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render  "layouts/footer" %>